/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import static Database.Conexion.getConnection;
import static Database.LoginDB.validateUserName;
import java.security.Principal;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Gerar
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblpass = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(33, 162, 248));
        setResizable(false);

        lblLogin.setBackground(new java.awt.Color(255, 255, 255));
        lblLogin.setBorder(new javax.swing.border.MatteBorder(null));
        lblLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cocinero.png"))); // NOI18N
        lblImage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLogin.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 7, 309, 428));

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        lblTitulo.setText("Panaderia Vazquéz");
        lblLogin.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 47, 194, -1));

        lblUser.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblUser.setText("Usuario");
        lblLogin.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 116, 70, 33));

        txtUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        lblLogin.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 117, 167, 33));

        lblpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblpass.setText("Contraseña");
        lblLogin.add(lblpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 186, -1, -1));

        txtPassword.setToolTipText("");
        txtPassword.setDoubleBuffered(true);
        txtPassword.setDragEnabled(true);
        lblLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 178, 167, 39));

        btnLogin.setBackground(new java.awt.Color(78, 58, 213));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Iniciar sesion");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLogin.setDefaultCapable(false);
        btnLogin.setFocusCycleRoot(true);
        btnLogin.setInheritsPopupMenu(true);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        lblLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 253, 211, 42));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        String user = txtUser.getText();
        String password = txtPassword.getText();

        Connection conexion = getConnection();

        try {
            boolean m = validateUserName(user, password, conexion);

            if (m) {
                Inicio main = new Inicio();
                main.setVisible(m);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(rootPane, "USUARIO NO EXISTE");

            }
        } catch (Exception e) {
        }



    }//GEN-LAST:event_btnLoginActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblImage;
    private javax.swing.JPanel lblLogin;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblpass;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
